MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
#  WEIGHT: '/home/jayeon/Documents/EveryPixelMatters/pretrained/vgg16_caffe-292e1171.pth'
#  WEIGHT: "/home/jayeon/Documents/EveryPixelMatters/pretrained/grad_clip/Sim10k_ga_initlr_0.01_lr_decay_grad_clip/model_final.pth" # Initialed by GA pretrained weight (Optimizer and scheduler should not be loaded)
#  WEIGHT: "/home/jayeon/Documents/EveryPixelMatters/pretrained/grad_clip/Sim10k_ga_initlr_0.01_lr_decay_grad_clip/best_model/cityscapes_val_caronly_cocostyle/best_model.pth" # Initialed by GA pretrained weight (Optimizer and scheduler should not be loaded)
# WEIGHT: "/home/jayeon/Documents/EveryPixelMatters/pretrained/Sim10k_ga_ca_initlr_0.01_lr_decay/best_model/cityscapes_val_caronly_cocostyle/best_model.pth" # Initialed by GA pretrained weight (Optimizer and scheduler should not be loaded)
# WEIGHT: "/home/jayeon/Documents/MLVU/EveryPixelMatters/training_dir/GA_CondA_REG_TOP_SIM10k_VGG16_SMOOTH_ALPHA0.2_SOFT_PROB_TAU_0.1_WEAK_SUP_FROM_SCRATCH/model_best.pth" # Initialed by GA pretrained weight (Optimizer and scheduler should not be loaded)
#  WEIGHT: '/home/jayeon/Documents/EveryPixelMatters/training_dir/SourceOnly_SIM10k2CS_VGG16/model_best.pth' # Initialed by GA pretrained weight (Optimizer and scheduler should not be loaded)
#  WEIGHT: '/home/jayeon/Documents/MLVU/EveryPixelMatters/training_dir/GA_CondA_REG_LEFT_SIM10k_VGG16_SMOOTH_ALPHA0.2_SOFT_PROB_TAU_0.1_WEAK_SUP_CF0.5/model_best.pth' # Initialed by GA pretrained weight (Optimizer and scheduler should not be loaded)
#  WEIGHT: '/home/jayeon/Documents/EveryPixelMatters/training_dir/Oracle_Sim10k/model_best.pth' # Initialed by GA pretrained weight (Optimizer and scheduler should not be loaded)
  WEIGHT: '/home/jayeon/Documents/MLVU/EveryPixelMatters/training_dir/GA_CondA_REG_SEPERATE_LEFT_TOP_SIM10k_VGG16_SMOOTH_ALPHA0.2_CF0.5/model_best.pth' # Initialed by GA pretrained weight (Optimizer and scheduler should not be loaded)
#  WEIGHT: '/home/jayeon/Documents/MLVU/EveryPixelMatters/training_dir/GA_CA_CondA_REG_SIM10k_2/model_best.pth' # Initialed by GA pretrained weight (Optimizer and scheduler should not be loaded)
  #
  RPN_ONLY: True
  FCOS_ON: True
  DA_ON: True
  BACKBONE:
    CONV_BODY: "VGG-16-FPN-RETINANET"
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    NUM_CLASSES: 2
    INFERENCE_TH: 0.05    # pre_nms_thresh    (default=0.05)
    PRE_NMS_TOP_N: 1000   # pre_nms_top_n     (default=1000)
    NMS_TH: 0.6           # nms_thresh        (default=0.6)
  ADV:
    #
    SEPERATE_DIS: True
    USE_DIS_GLOBAL: False
    USE_DIS_CENTER_AWARE: False
    USE_DIS_CONDITIONAL: False
    CENTER_AWARE_WEIGHT: 20
    CENTER_AWARE_TYPE: "ca_feature" # or "ca_loss"
    #
    COND_EXPAND: 0
    COND_SMOOTH: True
    COND_WARMUP_ITER: 6000
    COND_ALPHA: 0.2
    COND_CONF: 0.7
    COND_CLASS: False
    COND_REG:
      LEFT: False
      TOP: True
    #
    GA_DIS_LAMBDA: 0.01
    CA_DIS_LAMBDA: 0.1
    COND_DIS_LAMBDA: 0.1
    GRL_APPLIED_DOMAIN: 'both'
    #
    USE_DIS_P7: True
    USE_DIS_P6: True
    USE_DIS_P5: True
    USE_DIS_P4: True
    USE_DIS_P3: True
    #
    DIS_P7_NUM_CONVS: 4
    DIS_P6_NUM_CONVS: 4
    DIS_P5_NUM_CONVS: 4
    DIS_P4_NUM_CONVS: 4
    DIS_P3_NUM_CONVS: 4
    #
    CA_DIS_P7_NUM_CONVS: 4
    CA_DIS_P6_NUM_CONVS: 4
    CA_DIS_P5_NUM_CONVS: 4
    CA_DIS_P4_NUM_CONVS: 4
    CA_DIS_P3_NUM_CONVS: 4
    #
    COND_DIS_P7_NUM_CONVS: 4
    COND_DIS_P6_NUM_CONVS: 4
    COND_DIS_P5_NUM_CONVS: 4
    COND_DIS_P4_NUM_CONVS: 4
    COND_DIS_P3_NUM_CONVS: 4
    #
    GRL_WEIGHT_P7: 0.02
    GRL_WEIGHT_P6: 0.02
    GRL_WEIGHT_P5: 0.02
    GRL_WEIGHT_P4: 0.02
    GRL_WEIGHT_P3: 0.02
    #
    CA_GRL_WEIGHT_P7: 0.02
    CA_GRL_WEIGHT_P6: 0.02
    CA_GRL_WEIGHT_P5: 0.02
    CA_GRL_WEIGHT_P4: 0.02
    CA_GRL_WEIGHT_P3: 0.02
    #
    COND_GRL_WEIGHT_P7: 0.2
    COND_GRL_WEIGHT_P6: 0.2
    COND_GRL_WEIGHT_P5: 0.2
    COND_GRL_WEIGHT_P4: 0.2
    COND_GRL_WEIGHT_P3: 0.2
TEST:
  DETECTIONS_PER_IMG: 100 # fpn_post_nms_top_n  (default=100)
DATASETS:
  TRAIN_SOURCE: ("sim10k_trainval_caronly", )
  TRAIN_TARGET: ("cityscapes_train_caronly_cocostyle", )
  TEST: ("cityscapes_val_caronly_cocostyle", )
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  WEIGHT_DECAY: 0.0001
  MAX_ITER: 20000
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 500
  #
  BACKBONE:
    BASE_LR: 0.01
    STEPS: (12000, 18000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"
  #
  FCOS:
    BASE_LR: 0.01
    STEPS: (12000, 18000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"
  #
  DIS:
    BASE_LR: 0.01
    STEPS: (12000, 18000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"
