MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: '/home/jayeon/Documents/EveryPixelMatters/pretrained/vgg16_caffe-292e1171.pth' # Initialed by pretrained weight
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "VGG-16-FPN-RETINANET"
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
  FCOS:
    NUM_CLASSES: 2
    INFERENCE_TH: 0.05    # pre_nms_thresh    (default=0.05)
    PRE_NMS_TOP_N: 1000   # pre_nms_top_n     (default=1000)
    NMS_TH: 0.6           # nms_thresh        (default=0.6)
TEST:
  DETECTIONS_PER_IMG: 100 # fpn_post_nms_top_n  (default=100)
DATASETS:
  TRAIN_SOURCE: ("kitti_train_caronly", )  # In the case of Oracle, put "cityscapes_train_caronly_cocostyle"
  TEST: ("cityscapes_val_caronly_cocostyle", )
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  WEIGHT_DECAY: 0.0001
  MAX_ITER: 20000
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 500
  #
  BACKBONE:
    BASE_LR: 0.005
    STEPS: (12000, 18000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"
  #
  FCOS:
    BASE_LR: 0.005
    STEPS: (12000, 18000)
    WARMUP_ITERS: 500
    WARMUP_METHOD: "constant"